### ISSUE TITLE
some documentation plz

### ISSUE THREAD

**Issue by xgrons** [call-042PE/JNIStuff#1]
some documentation plz

**Comment by call-042PE** [comment]
What documentation ?

**Comment by xgrons** [comment]
how to use it plz

**Comment by call-042PE** [comment]
Well it's not ready to paste but im gonna give you some info.
So, this is a JNI DLL its for interacting with the JAVA virtual machine, In java they are classes,fields,obj,etc..
This DLL as been made for cracking a special checker with keyauth which i will not release, but im pretty sure it can work on other keyauth program written in JAVA, so all you have to do is start your jadx decompiler and change the classes and fields.
If you have others questions, tell me 👍

**Comment by xgrons** [comment]
Thank you very much, I appreciate all your help and support.
